### ISSUE TITLE
Suspicious error log messages

### ISSUE THREAD

**Issue by slact** [slact/nchan#349]
@TrustNoOne: 
``` 
2017/04/24 08:20:48 [error] 14#14: SUB:LONGPOLL:abort! unknown error
2017/04/24 11:40:00 [error] 8#8: nchan: A message from the past has just been published. Unless the system time has been adjusted, this should never happen.
2017/04/24 11:40:00 [error] 8#8: nchan: A message from the past has just been published. Unless the system time has been adjusted, this should never happen.
2017/04/24 17:49:09 [error] 13#13: MEMSTORE:06: multimsg 0000556740ECB940 timeout!!
2017/04/24 17:49:09 [error] 13#13: MEMSTORE:06: multimsg callback #-1 for 0000556740ECB940 received after expiring at 1493056149 status 4 msg 0000000000000000
2017/04/24 17:49:09 [error] 13#13: MEMSTORE:06: multimsg callback #-1 for 0000556740ECB940 received after expiring at 1493056149 status 4 msg 0000000000000000
```

**Comment by TrustNoOne** [comment]
The problem here is I literally got those 5 times in two days, I wouldn't know how to cause them

**Comment by slact** [comment]
That's okay, I just want to take a look at what's going on when these messages happen. You up for a few more coredumps?

First up, `SUB:LONGPOLL:abort! unknown error`.

Checkout branch **349-debug**, build & run with with coredump-friendly cflags as before. Nginx will crash right after that message.

**Comment by TrustNoOne** [comment]
I already built a couple of scripts to build and run everything easily after the third or fourth dump, I should be given some ambiguous title like "hard-core dump master" or similar haha :D

Apart from silly jokes... it's up and running, I'll post the links as usual when it crashes

**Comment by TrustNoOne** [comment]
@slact [got it](https://hastebin.com/efogicinuk.txt)

[core dump](https://we.tl/fObvLgmrVc)

**Comment by slact** [comment]
Ah, the dump-master delivers.

**Comment by slact** [comment]
Ok, I think this is not significant. Most likely, there was a failure to write a message to a connection's socket because the connection was aborted, but before the connection_close event was processed. This might have to do with the `--with-threads` and `--with-file-aio` configure settings. If you want to dig a little deeper on this, rebuild without those settings, or we could move on to the next item.

**Comment by TrustNoOne** [comment]
is it supposed to crash without those settings as well?  

I guess the other errors could be investigated first and then we could possibly get back to whichever looks the most dangerous, since this one is probably not critical

**Comment by slact** [comment]
None of these are crash-worthy. I just added a crash in there in 349-debug so I could look at what's causing these unusual errors in the log.

So moving on to `message from the past` errors. Same deal, rebuild from **349-debug** and run.

**Comment by TrustNoOne** [comment]
[here we go](https://hastebin.com/moyotesege.txt)
[crash dump](https://we.tl/ECzPmk04m3)

**Comment by slact** [comment]
So this `message from the past` this is the result of published messages arriving slightly delayed from different workers. The message timestamp was being generated at the time the request is received, but it should be generated at the time the message is stored. It's plausible that this could have resulted in subscribers missing out-of-order messages, but I haven't seen it in the wild. 

Anyway, fixed in 9c27cb86ee11b68bb0a. Rebuild 349-debug, you shouldn't get any more `message from the past` errors. After that, we'll move onto the `multimsg timeout` one.

**Comment by TrustNoOne** [comment]
Alright, I guess  the assertion for the new one could be added while checking that message from the past errors don't happen at the same time? I'm building the current 349-debug meanwhile

**Comment by slact** [comment]
One thing at a time. These hard-to-reproduce bugs are pretty finicky, as I'm sure you've noticed.

The `multimsg timeout` thing, by the way, has been around for a while and all it seems to cause is a hundred bytes' worth of memory leaking. I definitely want to investigate it, but it's not exactly a show-stopper. First let's check the fix.

**Comment by TrustNoOne** [comment]
Ok no problem :) 
the mulitmsg timeout is indeed *much* more rare than the other two, I haven't seen one in all the tests I made after it first showed up. 

I'll report here if  the log is clear from `message from the past` errors, starting it now

**Comment by TrustNoOne** [comment]
You were right, [it's still crashing](https://hastebin.com/ovipecoqav.txt)

[core dump](https://we.tl/yeCR1NTVnd)

**Comment by slact** [comment]
[That ought to do it](https://github.com/slact/nchan/commit/424f314d7a759f6d15a9f4b89229470b40b52c8f). Rinse, repeat.

**Comment by TrustNoOne** [comment]
Alright, I was away for the weekend, starting it now

**Comment by slact** [comment]
Just released 1.1.5 which includes this fix. Thanks for all your debugging!
