### ISSUE TITLE
Malformed eventsource messages when delived during nchan_subrequest

### ISSUE THREAD

**Issue by shtinkov** [slact/nchan#422]
#Hello,
Iam trying to test eventousrce with nchan.
Server is Debian/stretch with nginx-1.13.3 and nchan from master branch (27.11.2017 with latest more delayed-ipc fixing).
Here is my nchan configuration:
```nginx
location /test/publish {
    nchan_channel_id $arg_channel;
    nchan_message_timeout 20s;
    nchan_publisher;
}
location /test/subscribe {
    nchan_channel_id $arg_channel;
    nchan_subscriber eventsource;
    nchan_subscriber_first_message newest;
    nchan_subscribe_request /test/post_msg;
 }
 location = /test/post_msg {
    internal;
    proxy_pass $scheme://$server_addr:$server_port/test/publish?channel=$arg_park/0/0;
    proxy_cache off;
    proxy_method POST;
    proxy_set_header Accept text/json;
    proxy_set_header Content-Type text/json;
    proxy_set_body "{\"device_id\":$arg_device, \"purpose\":$arg_purpose, \"qtype\":\"$arg_qtype\", \"value\":\"$arg_value\",\"channel\":\"$arg_channel\"}";
 }
```
Testing is done in a following way
In my first terminal i start:

curl --request GET -H "Accept: text/event-stream" "https://inovent.bg/test/subscribe?channel=1/0/0&park=1&device=0&purpose=3&qtype=subscription"
which produces:
": hi"

on my second terminal i invoke the same:
curl --request GET -H "Accept: text/event-stream" "https://inovent.bg/test/subscribe?channel=1/0/0&park=1&device=0&purpose=3&qtype=subscription"

then on first terminal appears:
 1511853461:0id: {"device_id":0, "purpose":3, "qtype":"subscription", "value":"","channel":"1/0/0"}data:

You can see that message is malformed 

You can check the situation also online because server is up and running

**Comment by slact** [comment]
Confirmed, looking into it.

**Comment by slact** [comment]
that was a weird one. fixed in ade17335

**Comment by shtinkov** [comment]
Thank you very much for the patch! I tested, and it works perfectly!

**Comment by shtinkov** [comment]
Hi,
I use debian stretch, and the only solution for me is my own build. Even in backports nchan version is 1.0.8.

**Comment by nkuehn** [comment]
Thanks!
Just saw that nchan has a test / internal build that includes openresty, I'll try to run that to get a binary for my needs:  https://github.com/slact/nchan/blob/master/dev/rebuild.sh#L108

**Comment by neben** [comment]
This is still happening on nchan version 1.1.15, probably connected to `nchan_subscribe_request` handler posting back to the original pubsub location.  The corrupted frame looks like this:
```
foo:subscribed

1528406275:[0],0id: 
```
nginx/nchan config:
```
	location = /pubsub {
		nchan_pubsub;
		nchan_subscriber_channel_id $arg_sub;
		nchan_publisher_channel_id $arg_pub;
		nchan_channel_id_split_delimiter ",";
		nchan_message_buffer_length 1;
		nchan_message_timeout 1w;
		nchan_max_channel_id_length 4096;
		nchan_channel_group "self";
		nchan_subscribe_request /pubsub/sub;
		nchan_unsubscribe_request /pubsub/unsub;
	}

	location = /pubsub/sub {
		internal;
		keepalive_timeout 0;
		content_by_lua_block {
			ngx.eof()
			local id = ngx.var.nchan_channel_id or 'empty'
			local http = require "resty.http"
			local httpc = http.new()
			httpc:set_timeout(500)
			httpc:connect("127.0.0.1", 8080)
			local res, err = httpc:request({
				path = "/pubsub?pub=sub,all," .. id,
				headers = {
					["Host"] = "[hidden]",
				},
				method = "POST",
				body = id .. ':subscribed'
			})
		}
	}
```
nginx version:
```
# nginx -V
nginx version: nginx/1.13.12
built by gcc 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) 
built with OpenSSL 1.1.0f  25 May 2017
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-g -O2 -fdebug-prefix-map=/data/builder/debuild/nginx-1.13.12/debian/debuild-base/nginx-1.13.12=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC' --with-ld-opt='-specs=/usr/share/dpkg/no-pie-link.specs -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie'
```
nchan stats:
```
total published messages: 1015
stored messages: 43
shared memory used: 40K
shared memory limit: 131072K
channels: 65
subscribers: 12
redis pending commands: 0
redis connected servers: 0
total interprocess alerts received: 298130
interprocess alerts in transit: 0
interprocess queued alerts: 0
total interprocess send delay: 0
total interprocess receive delay: 0
nchan version: 1.1.15
```
